fspotfinder: FSpotFinder.cpp LotLayout.cpp LotLayout.hpp
	g++ LotLayout.hpp LotLayout.cpp FSpotFinder.cpp -o FSpotFinder -I ~/Projects/FSpotFinder -L ~/Projects/FSpotFinder -I /usr/local/include/opencv -I/usr/include/libxml2 -L /home/elguapo/Desktop/OpenCV-2.0.0/latest_tested_snapshot/opencv/release/lib -lcxcore -lcv -lcvaux -lhighgui -lml -lxml2

